// soc_system_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module soc_system_mm_interconnect_0 (
		input  wire        clk_0_clk_clk,                                    //                                  clk_0_clk.clk
		input  wire        fifo_f2h_in_mm_reset_reset_bridge_in_reset_reset, // fifo_f2h_in_mm_reset_reset_bridge_in_reset.reset
		input  wire [2:0]  fifo_f2h_in_mm_avalon_master_address,             //               fifo_f2h_in_mm_avalon_master.address
		output wire        fifo_f2h_in_mm_avalon_master_waitrequest,         //                                           .waitrequest
		input  wire [3:0]  fifo_f2h_in_mm_avalon_master_byteenable,          //                                           .byteenable
		input  wire        fifo_f2h_in_mm_avalon_master_read,                //                                           .read
		output wire [31:0] fifo_f2h_in_mm_avalon_master_readdata,            //                                           .readdata
		input  wire        fifo_f2h_in_mm_avalon_master_write,               //                                           .write
		input  wire [31:0] fifo_f2h_in_mm_avalon_master_writedata,           //                                           .writedata
		output wire [0:0]  fifo_f2h_in_in_address,                           //                             fifo_f2h_in_in.address
		output wire        fifo_f2h_in_in_write,                             //                                           .write
		output wire [31:0] fifo_f2h_in_in_writedata                          //                                           .writedata
	);

	wire         fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_waitrequest;   // fifo_f2h_in_in_translator:uav_waitrequest -> fifo_f2h_in_mm_avalon_master_translator:uav_waitrequest
	wire  [31:0] fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_readdata;      // fifo_f2h_in_in_translator:uav_readdata -> fifo_f2h_in_mm_avalon_master_translator:uav_readdata
	wire         fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_debugaccess;   // fifo_f2h_in_mm_avalon_master_translator:uav_debugaccess -> fifo_f2h_in_in_translator:uav_debugaccess
	wire   [2:0] fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_address;       // fifo_f2h_in_mm_avalon_master_translator:uav_address -> fifo_f2h_in_in_translator:uav_address
	wire         fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_read;          // fifo_f2h_in_mm_avalon_master_translator:uav_read -> fifo_f2h_in_in_translator:uav_read
	wire   [3:0] fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_byteenable;    // fifo_f2h_in_mm_avalon_master_translator:uav_byteenable -> fifo_f2h_in_in_translator:uav_byteenable
	wire         fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_readdatavalid; // fifo_f2h_in_in_translator:uav_readdatavalid -> fifo_f2h_in_mm_avalon_master_translator:uav_readdatavalid
	wire         fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_lock;          // fifo_f2h_in_mm_avalon_master_translator:uav_lock -> fifo_f2h_in_in_translator:uav_lock
	wire         fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_write;         // fifo_f2h_in_mm_avalon_master_translator:uav_write -> fifo_f2h_in_in_translator:uav_write
	wire  [31:0] fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_writedata;     // fifo_f2h_in_mm_avalon_master_translator:uav_writedata -> fifo_f2h_in_in_translator:uav_writedata
	wire   [2:0] fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_burstcount;    // fifo_f2h_in_mm_avalon_master_translator:uav_burstcount -> fifo_f2h_in_in_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (3),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (3),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) fifo_f2h_in_mm_avalon_master_translator (
		.clk                    (clk_0_clk_clk),                                                                   //                       clk.clk
		.reset                  (fifo_f2h_in_mm_reset_reset_bridge_in_reset_reset),                                //                     reset.reset
		.uav_address            (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (fifo_f2h_in_mm_avalon_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (fifo_f2h_in_mm_avalon_master_waitrequest),                                        //                          .waitrequest
		.av_byteenable          (fifo_f2h_in_mm_avalon_master_byteenable),                                         //                          .byteenable
		.av_read                (fifo_f2h_in_mm_avalon_master_read),                                               //                          .read
		.av_readdata            (fifo_f2h_in_mm_avalon_master_readdata),                                           //                          .readdata
		.av_write               (fifo_f2h_in_mm_avalon_master_write),                                              //                          .write
		.av_writedata           (fifo_f2h_in_mm_avalon_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                            //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                            //               (terminated)
		.av_begintransfer       (1'b0),                                                                            //               (terminated)
		.av_chipselect          (1'b0),                                                                            //               (terminated)
		.av_readdatavalid       (),                                                                                //               (terminated)
		.av_lock                (1'b0),                                                                            //               (terminated)
		.av_debugaccess         (1'b0),                                                                            //               (terminated)
		.uav_clken              (),                                                                                //               (terminated)
		.av_clken               (1'b1),                                                                            //               (terminated)
		.uav_response           (2'b00),                                                                           //               (terminated)
		.av_response            (),                                                                                //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                            //               (terminated)
		.av_writeresponsevalid  ()                                                                                 //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (1),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (3),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) fifo_f2h_in_in_translator (
		.clk                    (clk_0_clk_clk),                                                                   //                      clk.clk
		.reset                  (fifo_f2h_in_mm_reset_reset_bridge_in_reset_reset),                                //                    reset.reset
		.uav_address            (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (fifo_f2h_in_mm_avalon_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (fifo_f2h_in_in_address),                                                          //      avalon_anti_slave_0.address
		.av_write               (fifo_f2h_in_in_write),                                                            //                         .write
		.av_writedata           (fifo_f2h_in_in_writedata),                                                        //                         .writedata
		.av_read                (),                                                                                //              (terminated)
		.av_readdata            (32'b11011110101011011101111010101101),                                            //              (terminated)
		.av_begintransfer       (),                                                                                //              (terminated)
		.av_beginbursttransfer  (),                                                                                //              (terminated)
		.av_burstcount          (),                                                                                //              (terminated)
		.av_byteenable          (),                                                                                //              (terminated)
		.av_readdatavalid       (1'b0),                                                                            //              (terminated)
		.av_waitrequest         (1'b0),                                                                            //              (terminated)
		.av_writebyteenable     (),                                                                                //              (terminated)
		.av_lock                (),                                                                                //              (terminated)
		.av_chipselect          (),                                                                                //              (terminated)
		.av_clken               (),                                                                                //              (terminated)
		.uav_clken              (1'b0),                                                                            //              (terminated)
		.av_debugaccess         (),                                                                                //              (terminated)
		.av_outputenable        (),                                                                                //              (terminated)
		.uav_response           (),                                                                                //              (terminated)
		.av_response            (2'b00),                                                                           //              (terminated)
		.uav_writeresponsevalid (),                                                                                //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                             //              (terminated)
	);

endmodule
